2022-02-09 19:27:36,537 ERROR: Unhandled exception [in /Users/ira/PycharmProjects/flask_project/./app/tasks.py:41]
Traceback (most recent call last):
  File "/Users/ira/PycharmProjects/flask_project/./app/tasks.py", line 32, in export_posts
    _('[Blog] Your blog posts'),
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/flask_babel/__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/flask_babel/__init__.py", line 586, in gettext
    t = self.get_translations()
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/flask_babel/__init__.py", line 554, in get_translations
    locale = get_locale()
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/flask_babel/__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
  File "/Users/ira/PycharmProjects/flask_project/./app/__init__.py", line 100, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/werkzeug/local.py", line 432, in __get__
    obj = instance._get_current_object()
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/werkzeug/local.py", line 554, in _get_current_object
    return self.__local()  # type: ignore
  File "/Users/ira/PycharmProjects/flask_project/venv/lib/python3.9/site-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
